### PR TITLE
Confirmation dialog for show all and hide maxCount

### PR DESCRIPTION
**Pull request by derekisbusy**
Added option to automatically add confirmation dialog if has more than confirm minCount.
Added toggle data option 'maxCount' to hide the toggle button if there are more than maxCount.

New toggle data options...

```php
[
    'maxCount' => 10000, // hide toggle button if more than 10000 rows
//    'confirm' => true, // always ask for confirmation
    'confirm' => [
        'minCount' => 1000 // Ask for confirmation if more than 1000
    ]
    'all' => [
        'icon' => 'resize-full',
        'label' => Yii::t('kvgrid', 'All'),
        'class' => 'btn btn-default',
        'title' => 'Show all data'
    ],
    'page' => [
        'icon' => 'resize-small',
        'label' => Yii::t('kvgrid', 'Page'),
        'class' => 'btn btn-default',
        'title' => 'Show first page data'
    ],
]
```

### CODE REVIEW

**Comment by kartik-v** [comment]
Thanks for the enhancement. Hope these are tested? I am merging them. 

Have a plan to use a JS messaging popup library instead of using native JS popups.

**Comment by derekisbusy** [comment]
Yeah I tested it. It's simple enhancement.

**Comment by kartik-v** [comment]
I made further enhancements to this. Using `data-confirm` was submitting the entire page and PJAX was broken. I made some javascript related event trapping and enhancements to ensure the grid is still refreshed via PJAX.

**Comment by derekisbusy** [comment]
Were you using the latest release of Yii2.. https://github.com/yiisoft/yii2/commit/17e2255472a2b1a30fb1ce42a8937793214bbc46

**Comment by kartik-v** [comment]
Not sure... need to check. In either case allowing the JS on click OR pjax:click to be registered separately is better because the GridView re-initializes all such script when a pjax reload is completed.

**Comment by kartik-v** [comment]
Seeing the above yii commit - it seems the page reload issue would be resolved. 

Still will retain all these through separate JS instead of yii's data confirm. I feel I will implement an option for using a separate JS library for message popups - since the native JS popup can be dismissed and skipped via the browser leading to issues.

**Pull request merged**
