### PR TITLE
Fix and improve german, italian and french translations

### PR DESCRIPTION
**Pull request by XzAeRo**
## Scope
This pull request includes a

- [ ] Bug fix
- [ ] New feature
- [x] Translation

## Changes
The following changes were made (this change is also documented in the [change log](https://github.com/kartik-v/yii2-grid/blob/master/CHANGE.md)):

- Fix and improve missing translation strings for german, italian and french.

## Related Issues

#702

### CODE REVIEW

**Comment by kartik-v** [comment]
Thanks.. just one change.. do not translate tokens that are within curly braces (as these will be parsed and replaced at runtime). For example do not translate **{item}** or **{items}**.

**Comment by kartik-v** [comment]
Check PR #698 (Spanish translation) for reference on how to translate.

**Comment by kartik-v** [comment]
I will update over this PR and merge this.

**Comment by XzAeRo** [comment]
Thank you!

**Pull request merged**
