### PR TITLE
fix for pjax gridview using expandRow with detailUrl pjax form

### PR DESCRIPTION
**Pull request by yavuzg2**
## Scope
This pull request includes a

- [ x ] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made (this change is also documented in the [change log](https://github.com/yavuzg2/yii2-grid/blob/master/CHANGE.md)):

Revision 2:
Adding to line 112 was problematic as well, instead I modified the code at line 239 as follows;
```
            if (isExpanded($icon)) {
                if(vInd !== undefined) {
                    if (detailUrl) {
                        loadDetail(function () {
                            expandRow(false);
                        });
                    } else {
                        expandRow(false);
                    }
                }
            }
```
I will repoen the pull request after more testing.

Revision 1:
Adding the code to line 103 broke expand / collapse all functionality. Moving the code to line 112 after "var loadDetail = function (postProcess) {" fixed the problem.

Initial release

Fix for pjax gridview using expandRow with detailUrl pjax form.

Problem: expanded rows disappear and new rows get added with data-index="undefined"

Steps to reproduce:
1. Expand two rows
2. When you submit the form on the second expanded row, the first row disappears

Fix: modify the following lines in /assets/js/kv-grid-expand.js at line 103

```
                    if(vInd === undefined) {
                        return;
                    }
```

See more details on change log.

## Related Issues
If this is related to an existing ticket, include a link to it as well.

### CODE REVIEW

**Comment by yavuzg2** [comment]
This change introduces new bugs.

**Comment by yavuzg2** [comment]
Revision 2 is stable

**Comment by kartik-v** [comment]
Thanks I will update over this in a bundled enhancement with a simpler check for this.

**Comment by kartik-v** [comment]
Resolved via [update to release v3.1.3](https://github.com/kartik-v/yii2-grid/commit/96a4c362353dc448e5317a52a5d244061e0244f8).

**Pull request closed without merging**
